# Generated by Django 4.2.7 on 2025-08-06 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_trainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gemini_api_key',
        ),
    ]
