# Generated by Django 4.2.7 on 2025-09-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_trainer', '0002_remove_userprofile_gemini_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='session_type',
            field=models.CharField(choices=[('operations', 'Operaciones y Producción'), ('sales_marketing', 'Ventas y Marketing'), ('finance', 'Finanzas y Administración'), ('hr', 'Recursos Humanos (Talento Humano)'), ('it', 'Tecnología de la Información (TI / IT)'), ('rd', 'Investigación y Desarrollo (I+D)'), ('customer_support', 'Atención al Cliente y Soporte'), ('management', 'Dirección General y Estratégica'), ('health', 'Salud y Medicina')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_interview_type',
            field=models.CharField(choices=[('operations', 'Operaciones y Producción'), ('sales_marketing', 'Ventas y Marketing'), ('finance', 'Finanzas y Administración'), ('hr', 'Recursos Humanos (Talento Humano)'), ('it', 'Tecnología de la Información (TI / IT)'), ('rd', 'Investigación y Desarrollo (I+D)'), ('customer_support', 'Atención al Cliente y Soporte'), ('management', 'Dirección General y Estratégica'), ('health', 'Salud y Medicina')], default='operations', max_length=20),
        ),
    ]
