# Generated by Django 4.2.7 on 2025-09-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_trainer', '0003_alter_interviewsession_session_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='questions_asked',
            field=models.IntegerField(default=0),
        ),
    ]
