# Generated by Django 4.2.7 on 2025-11-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_trainer', '0004_interviewsession_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_audio/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tts_voice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
