# Generated by Django 4.2.7 on 2025-11-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_trainer', '0005_chatmessage_audio_file_chatmessage_tts_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='last_resume_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='total_time_allowed',
            field=models.IntegerField(default=900, help_text='Tiempo total permitido en segundos'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='total_time_used',
            field=models.IntegerField(default=0, help_text='Tiempo utilizado acumulado en segundos'),
        ),
    ]
